import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import fetch from "node-fetch";

// ---- CONFIG ----
const INDEXNOW_KEY = "35b09db2cfb6456fb70a90685c0f11b2";
const HOST = "insuranceconsult.in";

// Path to sitemap generated by Astro build.
// Change if your sitemap output differs (e.g. dist/sitemap-index.xml).
const SITEMAP_PATH = process.env.SITEMAP_PATH || "dist/sitemap-0.xml";

// Snapshot file (committed or cached via CI artifact)
const SNAPSHOT_DIR = ".indexnow";
const SNAPSHOT_FILE = path.join(SNAPSHOT_DIR, "last-sitemap-urls.txt");

// IndexNow batch limit: keep conservative (Bing supports big batches, but safe chunking is better)
const BATCH_SIZE = 500;

// ---- HELPERS ----
function readFileSafe(p) {
  try {
    return fs.readFileSync(p, "utf8");
  } catch {
    return "";
  }
}

function extractLocUrlsFromSitemapXml(xml) {
  // Works for both sitemap.xml and sitemap index entries containing <loc>
  const urls = [];
  const re = /<loc>(.*?)<\/loc>/g;
  let m;
  while ((m = re.exec(xml)) !== null) {
    const u = (m[1] || "").trim();
    if (!u) continue;
    // Only keep your host URLs (defensive)
    if (u.includes(HOST)) urls.push(u.replace(/\/$/, "") + "/");
  }
  return [...new Set(urls)];
}

function toSet(linesText) {
  return new Set(
    linesText
      .split("\n")
      .map((x) => x.trim())
      .filter(Boolean)
      .map((u) => u.replace(/\/$/, "") + "/")
  );
}

function chunk(arr, size) {
  const out = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

async function postIndexNow(urlList) {
    console.log({urlList});
    // return { status: 200, body: "Mocked response" }; // MOCKED FOR TESTING
    
  const res = await fetch("https://api.indexnow.org/IndexNow", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      host: HOST,
      key: INDEXNOW_KEY,
      keyLocation: `https://${HOST}/${INDEXNOW_KEY}.txt`,
      urlList,
    }),
  });

  const text = await res.text().catch(() => "");
  return { status: res.status, body: text };
}

// ---- MAIN ----
async function run() {
  if (!INDEXNOW_KEY) {
    console.log("[IndexNow] Skipped: INDEXNOW_KEY not set");
    return;
  }

  const sitemapXml = readFileSafe(SITEMAP_PATH);
  if (!sitemapXml) {
    console.log(`[IndexNow] Skipped: Sitemap not found at ${SITEMAP_PATH}`);
    return;
  }

  const currentUrls = extractLocUrlsFromSitemapXml(sitemapXml);
  if (!currentUrls.length) {
    console.log("[IndexNow] Skipped: No URLs found in sitemap");
    return;
  }

  const prevUrls = toSet(readFileSafe(SNAPSHOT_FILE));
  const newUrls = currentUrls.filter((u) => !prevUrls.has(u));

  if (!newUrls.length) {
    console.log("[IndexNow] No new URLs. Skipping notify.");
    return;
  }

  console.log(`[IndexNow] New URLs detected: ${newUrls.length}`);

  // Notify in batches
  const batches = chunk(newUrls, BATCH_SIZE);
  for (const [i, batch] of batches.entries()) {
    const { status, body } = await postIndexNow(batch);
    console.log(`[IndexNow] Batch ${i + 1}/${batches.length} status: ${status}`);
    if (status >= 400) {
      console.log("[IndexNow] Response:", body.slice(0, 500));
      // Do NOT exit build; just report.
    }
  }

  // Update snapshot
  fs.mkdirSync(SNAPSHOT_DIR, { recursive: true });
  fs.writeFileSync(SNAPSHOT_FILE, currentUrls.join("\n") + "\n", "utf8");
  console.log("[IndexNow] Snapshot updated:", SNAPSHOT_FILE);
}

run().catch((e) => {
  console.log("[IndexNow] Error:", e?.message || e);
});
